[server]
maxUploadSize = 2048
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#d8ad57"
backgroundColor = "#17111f"
secondaryBackgroundColor = "#1e1630"
textColor = "#efe6dc"
