[server]
maxUploadSize = 2048
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#6d3fb0"
backgroundColor = "#f7f0e3"
secondaryBackgroundColor = "#fffdf9"
textColor = "#38291c"
